print("let\'s go!")
print(repr('let\"\ns go!'))
print(repr('let\'s ngo'))
print(repr('C:\nowhere'))
print(r'C:\nowhere''\\sad')

print('\u00C6')
print('\U0001F60A')
print('\U0001F60A')
print("this is a cat : \N{Cat}")
print(b'sad')
print("sad".encode("ASCII"))
print("sad".encode("UTF-8"))
print("sad".encode("UTF-32"))
